### ISSUE TITLE
How can I directly download Sentinel-1 images from Cerulean, along with data used for source identification?

### ISSUE THREAD

**Issue by geoexploring** [SkyTruth/cerulean-cloud#109]
@jonaraphael,  thank you for your excellent work. 

I would like to create a dataset using Cerulean's detection results, including Sentinel-1 images, AIS tracks, vessel identities, and offshore oil platform locations. 

How can I do this through Cerulean's API? Thanks

**Comment by jonaraphael** [comment]
Hello @geoexploring,
Thank you so much for reaching out--and for using our github repo! We need enthusiastic people like you to make sure we keep improving our services.

You can definitely use Cerulean's detection results to design and download a dataset. The data that you can download is primarily vector polygons and metadata about which S1 Scene ID produced the prediction. You can access the data here: [API](https://api.cerulean.skytruth.org/collections/public.slick_plus/items?f=geojson). And if you want to see some examples of how to filter those results, follow the first half of the readme in this repo: [README](https://github.com/SkyTruth/cerulean-cloud/blob/main/README.md)

We do not store the Sentinel-1 images for public download, but you can use the "s1_scene_id" column to find the corresponding image here: https://browser.dataspace.copernicus.eu/

Unfortunately our license agreement does not permit us to share AIS tracks directly with users, but you can consider a service like shipview.spire.com for historic tracks, or marinetraffic.com/ for recent and current tracks. Vessel identities, where we have them with high enough confidence will be shared in the graphical interface like this: https://www.cerulean.skytruth.org/?zoom=10.959216&lat=20.46457&lng=38.658423&slickId=408102

For offshore oil platform locations, we strongly recommend utilizing our partner, GFW's, dataset: https://globalfishingwatch.org/research-project-offshore-infrastructure/

I hope that this helps further your project! 

Please let us know what your intended use of the data is so that we can better support you in the future.

**Comment by geoexploring** [comment]
@jonaraphael , thank you for the information. 

I emailed `support@skytruth.org` on this Monday but haven't received a reply. Could you provide your email address? 

Thanks again.
